project:
  outputs:
    dev:
      type: materialize
      threads: 1
      host: materialized
      port: 6875
      user: materialize
      pass: password
      database: materialize
      schema: public

  target: dev