global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: materialize
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'materialized:6875'
  - job_name: event_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'exporter:80'
